using Assets._Game._Scripts._0.Data._Base;
using UnityEngine;

namespace Assets._Game._Scripts._0.Data._DataForUpgrade
{
    // Класс для данных прокачки столов разных типов продуктов 

    [CreateAssetMenu(fileName = "MechanicalEyeUpgradeData", menuName = "Game/MechanicalEyeDataForUpgrade")]
    public class MechanicalEyeUpgradeSO : BaseUpgradeSO {
        public override BaseDataForUpgrade[] Upgrades => _upgrades;

        [SerializeField]
        private MechanicalEyeDataForUpgrade[] _upgrades = new MechanicalEyeDataForUpgrade[]
        {
       new MechanicalEyeDataForUpgrade { Stars = 0, Level = 1, Cost = 10, IncomeMoney = 3, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 2, Cost = 3, IncomeMoney = 4, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 3, Cost = 4, IncomeMoney = 5, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 4, Cost = 6, IncomeMoney = 6, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 5, Cost = 8, IncomeMoney = 7, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 6, Cost = 11, IncomeMoney = 8, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 7, Cost = 14, IncomeMoney = 9, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 8, Cost = 18, IncomeMoney = 10, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 9, Cost = 23, IncomeMoney = 11, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 0, Level = 10, Cost = 29, IncomeMoney = 12, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 11, Cost = 37, IncomeMoney = 27, OpeningAtLevel = 1, Events = "Additional table opens" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 12, Cost = 47, IncomeMoney = 30, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 13, Cost = 60, IncomeMoney = 33, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 14, Cost = 76, IncomeMoney = 36, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 15, Cost = 96, IncomeMoney = 39, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 16, Cost = 121, IncomeMoney = 44, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 17, Cost = 153, IncomeMoney = 53, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 18, Cost = 193, IncomeMoney = 64, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 19, Cost = 244, IncomeMoney = 77, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 20, Cost = 308, IncomeMoney = 94, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 21, Cost = 389, IncomeMoney = 115, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 22, Cost = 491, IncomeMoney = 140, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 23, Cost = 619, IncomeMoney = 170, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 1, Level = 24, Cost = 780, IncomeMoney = 207, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 25, Cost = 983, IncomeMoney = 253, OpeningAtLevel = 1, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 26, Cost = 1240, IncomeMoney = 310, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 27, Cost = 1370, IncomeMoney = 332, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 28, Cost = 1510, IncomeMoney = 356, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 29, Cost = 1670, IncomeMoney = 383, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 30, Cost = 1840, IncomeMoney = 410, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 31, Cost = 2030, IncomeMoney = 441, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 32, Cost = 2240, IncomeMoney = 474, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 33, Cost = 2470, IncomeMoney = 510, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 34, Cost = 2720, IncomeMoney = 548, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 35, Cost = 3000, IncomeMoney = 590, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 36, Cost = 3300, IncomeMoney = 634, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 37, Cost = 3630, IncomeMoney = 682, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 38, Cost = 4000, IncomeMoney = 734, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 39, Cost = 4400, IncomeMoney = 790, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 40, Cost = 4840, IncomeMoney = 851, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 41, Cost = 5330, IncomeMoney = 918, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 42, Cost = 5870, IncomeMoney = 990, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 43, Cost = 6460, IncomeMoney = 1068, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 44, Cost = 7110, IncomeMoney = 1153, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 45, Cost = 7830, IncomeMoney = 1245, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 46, Cost = 8620, IncomeMoney = 1345, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 47, Cost = 9490, IncomeMoney = 1454, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 48, Cost = 10500, IncomeMoney = 1579, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 2, Level = 49, Cost = 11600, IncomeMoney = 1714, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 50, Cost = 12800, IncomeMoney = 1858, OpeningAtLevel = 2, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 51, Cost = 14100, IncomeMoney = 2012, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 52, Cost = 15600, IncomeMoney = 2188, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 53, Cost = 17200, IncomeMoney = 2373, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 54, Cost = 19000, IncomeMoney = 2579, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 55, Cost = 20900, IncomeMoney = 2791, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 56, Cost = 23000, IncomeMoney = 3023, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 57, Cost = 25300, IncomeMoney = 3273, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 58, Cost = 27900, IncomeMoney = 3555, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 59, Cost = 30700, IncomeMoney = 3852, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 60, Cost = 33800, IncomeMoney = 4178, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 61, Cost = 37200, IncomeMoney = 4532, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 62, Cost = 41000, IncomeMoney = 4922, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 63, Cost = 45100, IncomeMoney = 5338, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 64, Cost = 49700, IncomeMoney = 5800, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 65, Cost = 54700, IncomeMoney = 6295, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 66, Cost = 60200, IncomeMoney = 6834, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 67, Cost = 66300, IncomeMoney = 7425, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 68, Cost = 73000, IncomeMoney = 8067, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 69, Cost = 80300, IncomeMoney = 8757, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 70, Cost = 88400, IncomeMoney = 9516, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 71, Cost = 97300, IncomeMoney = 10341, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 72, Cost = 108000, IncomeMoney = 11333, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 73, Cost = 119000, IncomeMoney = 12332, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 3, Level = 74, Cost = 131000, IncomeMoney = 13409, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 75, Cost = 145000, IncomeMoney = 14662, OpeningAtLevel = 3, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 76, Cost = 160000, IncomeMoney = 15985, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 77, Cost = 176000, IncomeMoney = 17375, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 78, Cost = 194000, IncomeMoney = 18927, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 79, Cost = 214000, IncomeMoney = 20637, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 80, Cost = 236000, IncomeMoney = 22498, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 81, Cost = 260000, IncomeMoney = 24506, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 82, Cost = 286000, IncomeMoney = 26655, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 83, Cost = 315000, IncomeMoney = 29033, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 84, Cost = 347000, IncomeMoney = 31632, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 85, Cost = 382000, IncomeMoney = 34446, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 86, Cost = 421000, IncomeMoney = 37556, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 87, Cost = 464000, IncomeMoney = 40954, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 88, Cost = 511000, IncomeMoney = 44629, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 89, Cost = 563000, IncomeMoney = 48661, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 90, Cost = 620000, IncomeMoney = 53037, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 91, Cost = 682000, IncomeMoney = 57748, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 92, Cost = 751000, IncomeMoney = 62951, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 93, Cost = 827000, IncomeMoney = 68631, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 94, Cost = 910000, IncomeMoney = 74775, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 95, Cost = 1010000, IncomeMoney = 82181, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 96, Cost = 1120000, IncomeMoney = 90250, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 97, Cost = 1240000, IncomeMoney = 98963, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 98, Cost = 1370000, IncomeMoney = 108301, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 4, Level = 99, Cost = 1510000, IncomeMoney = 118246, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 5, Level = 100, Cost = 1670000, IncomeMoney = 129558, OpeningAtLevel = 4, Events = "" },
        new MechanicalEyeDataForUpgrade { Stars = 5, Level = 101, Cost = 0, IncomeMoney = 0, OpeningAtLevel = 5, Events = "" },
        };
    }

}