using Assets._Game._Scripts._0.Data._Base;
using UnityEngine;

namespace Assets._Game._Scripts._0.Data._DataForUpgrade
{
    [CreateAssetMenu(fileName = "RoboticArmUpgradeData", menuName = "Game/RoboticArmDataForUpgrade")]
    public class RoboticArmUpgradeSO : BaseUpgradeSO {
        public override BaseDataForUpgrade[] Upgrades => _upgrades;

        [SerializeField]
        private RoboticArmDataForUpgrade[] _upgrades = new RoboticArmDataForUpgrade[]
        {
        new RoboticArmDataForUpgrade { Stars = 0, Level = 1, Cost = 60, IncomeMoney = 15, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 2, Cost = 15, IncomeMoney = 17, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 3, Cost = 19, IncomeMoney = 19, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 4, Cost = 24, IncomeMoney = 21, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 5, Cost = 30, IncomeMoney = 23, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 6, Cost = 38, IncomeMoney = 25, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 7, Cost = 48, IncomeMoney = 27, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 8, Cost = 60, IncomeMoney = 30, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 9, Cost = 75, IncomeMoney = 33, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 10, Cost = 94, IncomeMoney = 36, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 11, Cost = 118, IncomeMoney = 45, OpeningAtLevel = 2, Events = "Additional table opens" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 12, Cost = 148, IncomeMoney = 54, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 13, Cost = 185, IncomeMoney = 65, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 14, Cost = 232, IncomeMoney = 78, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 15, Cost = 290, IncomeMoney = 94, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 16, Cost = 363, IncomeMoney = 113, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 17, Cost = 454, IncomeMoney = 136, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 18, Cost = 568, IncomeMoney = 165, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 19, Cost = 710, IncomeMoney = 199, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 20, Cost = 888, IncomeMoney = 241, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 21, Cost = 1110, IncomeMoney = 291, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 22, Cost = 1390, IncomeMoney = 354, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 23, Cost = 1740, IncomeMoney = 430, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 24, Cost = 1920, IncomeMoney = 460, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 25, Cost = 2120, IncomeMoney = 494, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 26, Cost = 2340, IncomeMoney = 531, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 27, Cost = 2580, IncomeMoney = 570, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 28, Cost = 2840, IncomeMoney = 611, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 29, Cost = 3130, IncomeMoney = 656, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 30, Cost = 3450, IncomeMoney = 706, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 31, Cost = 3800, IncomeMoney = 758, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 32, Cost = 4180, IncomeMoney = 815, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 33, Cost = 4600, IncomeMoney = 876, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 34, Cost = 5060, IncomeMoney = 942, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 35, Cost = 5570, IncomeMoney = 1015, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 36, Cost = 6130, IncomeMoney = 1093, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 37, Cost = 6750, IncomeMoney = 1178, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 38, Cost = 7430, IncomeMoney = 1270, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 39, Cost = 8180, IncomeMoney = 1370, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 40, Cost = 9000, IncomeMoney = 1478, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 41, Cost = 9900, IncomeMoney = 1594, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 42, Cost = 10900, IncomeMoney = 1722, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 43, Cost = 12000, IncomeMoney = 1860, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 44, Cost = 13200, IncomeMoney = 2009, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 45, Cost = 14600, IncomeMoney = 2182, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 46, Cost = 16100, IncomeMoney = 2364, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 47, Cost = 17800, IncomeMoney = 2569, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 48, Cost = 19600, IncomeMoney = 2780, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 49, Cost = 21600, IncomeMoney = 3013, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 50, Cost = 23800, IncomeMoney = 3265, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 51, Cost = 26200, IncomeMoney = 3536, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 52, Cost = 28900, IncomeMoney = 3838, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 53, Cost = 31800, IncomeMoney = 4157, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 54, Cost = 35000, IncomeMoney = 4505, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 55, Cost = 38500, IncomeMoney = 4880, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 56, Cost = 42400, IncomeMoney = 5293, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 57, Cost = 46700, IncomeMoney = 5744, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 58, Cost = 51400, IncomeMoney = 6230, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 59, Cost = 56600, IncomeMoney = 6762, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 60, Cost = 62300, IncomeMoney = 7338, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 61, Cost = 68600, IncomeMoney = 7967, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 62, Cost = 75500, IncomeMoney = 8648, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 63, Cost = 83100, IncomeMoney = 9390, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 64, Cost = 91500, IncomeMoney = 10201, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 65, Cost = 101000, IncomeMoney = 11111, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 66, Cost = 112000, IncomeMoney = 12161, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 67, Cost = 124000, IncomeMoney = 13290, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 68, Cost = 137000, IncomeMoney = 14497, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 69, Cost = 151000, IncomeMoney = 15778, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 70, Cost = 167000, IncomeMoney = 17234, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 71, Cost = 184000, IncomeMoney = 18756, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 72, Cost = 203000, IncomeMoney = 20443, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 73, Cost = 224000, IncomeMoney = 22289, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 74, Cost = 247000, IncomeMoney = 24287, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 75, Cost = 272000, IncomeMoney = 26433, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 76, Cost = 300000, IncomeMoney = 28818, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 77, Cost = 330000, IncomeMoney = 31339, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 78, Cost = 363000, IncomeMoney = 34085, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 79, Cost = 400000, IncomeMoney = 37140, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 80, Cost = 440000, IncomeMoney = 40404, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 81, Cost = 484000, IncomeMoney = 43960, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 82, Cost = 533000, IncomeMoney = 47889, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 83, Cost = 587000, IncomeMoney = 52178, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 84, Cost = 646000, IncomeMoney = 56816, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 85, Cost = 711000, IncomeMoney = 61880, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 86, Cost = 783000, IncomeMoney = 67442, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 87, Cost = 862000, IncomeMoney = 73487, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 88, Cost = 949000, IncomeMoney = 80084, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 89, Cost = 1050000, IncomeMoney = 87719, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 90, Cost = 1160000, IncomeMoney = 95947, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 91, Cost = 1280000, IncomeMoney = 104832, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 92, Cost = 1410000, IncomeMoney = 114355, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 93, Cost = 1560000, IncomeMoney = 125301, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 94, Cost = 1720000, IncomeMoney = 136834, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 95, Cost = 1900000, IncomeMoney = 149724, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 96, Cost = 2090000, IncomeMoney = 163154, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 97, Cost = 2300000, IncomeMoney = 177881, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 98, Cost = 2530000, IncomeMoney = 193870, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 99, Cost = 2790000, IncomeMoney = 211845, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 5, Level = 100, Cost = 3070000, IncomeMoney = 231001, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 5, Level = 101, Cost = 0, IncomeMoney = 0, OpeningAtLevel = 5, Events = "" },
        };
    }
}