using Assets._Game._Scripts._0.Data._Base;
using UnityEngine;

namespace Assets._Game._Scripts._0.Data._DataForUpgrade
{
    [CreateAssetMenu(fileName = "RoboticArmUpgradeData", menuName = "Game/RoboticArmDataForUpgrade")]
    public class RoboticArmUpgradeSO : BaseUpgradeSO {
        public override BaseDataForUpgrade[] Upgrades => _upgrades;

        [SerializeField]
        private RoboticArmDataForUpgrade[] _upgrades = new RoboticArmDataForUpgrade[]
        {
        new RoboticArmDataForUpgrade { Stars = 0, Level = 1, Cost = 25, IncomeMoney = 5, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 2, Cost = 8, IncomeMoney = 6, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 3, Cost = 10, IncomeMoney = 7, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 4, Cost = 13, IncomeMoney = 8, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 5, Cost = 17, IncomeMoney = 9, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 6, Cost = 22, IncomeMoney = 10, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 7, Cost = 28, IncomeMoney = 11, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 8, Cost = 35, IncomeMoney = 12, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 9, Cost = 44, IncomeMoney = 13, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 0, Level = 10, Cost = 55, IncomeMoney = 15, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 11, Cost = 69, IncomeMoney = 38, OpeningAtLevel = 2, Events = "Additional table opens" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 12, Cost = 87, IncomeMoney = 42, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 13, Cost = 109, IncomeMoney = 46, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 14, Cost = 137, IncomeMoney = 50, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 15, Cost = 172, IncomeMoney = 54, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 16, Cost = 215, IncomeMoney = 59, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 17, Cost = 269, IncomeMoney = 64, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 18, Cost = 337, IncomeMoney = 70, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 19, Cost = 422, IncomeMoney = 76, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 20, Cost = 528, IncomeMoney = 213, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 21, Cost = 660, IncomeMoney = 231, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 22, Cost = 825, IncomeMoney = 250, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 23, Cost = 1030, IncomeMoney = 270, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 1, Level = 24, Cost = 1290, IncomeMoney = 292, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 25, Cost = 1610, IncomeMoney = 537, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 26, Cost = 1930, IncomeMoney = 644, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 27, Cost = 2320, IncomeMoney = 774, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 28, Cost = 2780, IncomeMoney = 927, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 29, Cost = 3340, IncomeMoney = 1110, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 30, Cost = 4010, IncomeMoney = 1340, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 31, Cost = 4810, IncomeMoney = 1600, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 32, Cost = 5770, IncomeMoney = 1920, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 33, Cost = 6920, IncomeMoney = 2310, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 34, Cost = 8300, IncomeMoney = 2770, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 35, Cost = 9960, IncomeMoney = 3320, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 36, Cost = 12000, IncomeMoney = 4000, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 37, Cost = 14400, IncomeMoney = 4800, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 38, Cost = 17300, IncomeMoney = 5770, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 39, Cost = 20800, IncomeMoney = 6930, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 40, Cost = 25000, IncomeMoney = 8330, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 41, Cost = 30000, IncomeMoney = 10000, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 42, Cost = 36000, IncomeMoney = 12000, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 43, Cost = 43200, IncomeMoney = 14400, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 44, Cost = 51800, IncomeMoney = 17300, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 45, Cost = 62200, IncomeMoney = 20700, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 46, Cost = 74600, IncomeMoney = 24900, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 47, Cost = 89500, IncomeMoney = 29800, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 48, Cost = 107000, IncomeMoney = 35700, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 2, Level = 49, Cost = 128000, IncomeMoney = 42700, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 50, Cost = 154000, IncomeMoney = 51300, OpeningAtLevel = 2, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 51, Cost = 185000, IncomeMoney = 61700, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 52, Cost = 202000, IncomeMoney = 67300, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 53, Cost = 220000, IncomeMoney = 73300, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 54, Cost = 240000, IncomeMoney = 80000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 55, Cost = 262000, IncomeMoney = 87300, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 56, Cost = 286000, IncomeMoney = 95300, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 57, Cost = 312000, IncomeMoney = 104000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 58, Cost = 340000, IncomeMoney = 113000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 59, Cost = 371000, IncomeMoney = 124000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 60, Cost = 404000, IncomeMoney = 135000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 61, Cost = 440000, IncomeMoney = 147000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 62, Cost = 480000, IncomeMoney = 160000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 63, Cost = 523000, IncomeMoney = 174000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 64, Cost = 570000, IncomeMoney = 178000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 65, Cost = 621000, IncomeMoney = 194000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 66, Cost = 677000, IncomeMoney = 212000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 67, Cost = 738000, IncomeMoney = 231000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 68, Cost = 804000, IncomeMoney = 251000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 69, Cost = 876000, IncomeMoney = 274000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 70, Cost = 955000, IncomeMoney = 298000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 71, Cost = 1040000, IncomeMoney = 325000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 72, Cost = 1130000, IncomeMoney = 332000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 73, Cost = 1230000, IncomeMoney = 362000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 3, Level = 74, Cost = 1340000, IncomeMoney = 394000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 75, Cost = 1460000, IncomeMoney = 429000, OpeningAtLevel = 3, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 76, Cost = 1590000, IncomeMoney = 468000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 77, Cost = 1730000, IncomeMoney = 509000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 78, Cost = 1890000, IncomeMoney = 525000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 79, Cost = 1930000, IncomeMoney = 536000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 80, Cost = 1970000, IncomeMoney = 547000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 81, Cost = 2010000, IncomeMoney = 558000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 82, Cost = 2050000, IncomeMoney = 569000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 83, Cost = 2090000, IncomeMoney = 581000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 84, Cost = 2130000, IncomeMoney = 576000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 85, Cost = 2170000, IncomeMoney = 586000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 86, Cost = 2210000, IncomeMoney = 597000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 87, Cost = 2250000, IncomeMoney = 608000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 88, Cost = 2300000, IncomeMoney = 622000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 89, Cost = 2350000, IncomeMoney = 635000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 90, Cost = 2400000, IncomeMoney = 649000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 91, Cost = 2450000, IncomeMoney = 662000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 92, Cost = 2500000, IncomeMoney = 676000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 93, Cost = 2550000, IncomeMoney = 689000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 94, Cost = 2600000, IncomeMoney = 703000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 95, Cost = 2650000, IncomeMoney = 716000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 96, Cost = 2700000, IncomeMoney = 730000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 97, Cost = 2750000, IncomeMoney = 743000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 98, Cost = 2810000, IncomeMoney = 759000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 4, Level = 99, Cost = 2870000, IncomeMoney = 776000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 5, Level = 100, Cost = 2930000, IncomeMoney = 792000, OpeningAtLevel = 4, Events = "" },
        new RoboticArmDataForUpgrade { Stars = 5, Level = 101, Cost = 0, IncomeMoney = 0, OpeningAtLevel = 5, Events = "" },
        };
    }
}